language: node_js
node_js:
- stable
catche:
  directories:
  - node_modules
script:
- npm run coverage
deploy:
  provider: heroku
  api_key:
    secure: A4U6yufINEwr5Dh1ue9OoTnvWqWzt9dSorJ6zBs7DHD5I2CCjmPDzrBbEMkZobxuf256wTbIsqYb0+1w4QDB5+rN6HZyPoCB5KmLWaZBomcsL2P4sja4eeO0Eauysh9LxeidOFwFOtHyvyplcch+OoTx0Ctc3vyR2O/9BMrJggLhtpvJCQx1zLlfd2WS9FYCuhLFZTzn4bok1O4hWUQCV7Ghps2tmkApNvWo8eR2QoEopSbbvn43IdzSFuvMGJKVM8Va1ie+/e9XAR4th0MpXD96ZOkGeb8tWK1K8iaLKvPq45VNhoP0JY0CEF6CXE+eHnlB71j8KD75LgomIC7Ux2/bbWc23UKp34bVEMOsv0LMm6xWvhjsN+SQCzbYEbnheSjOhS8Er+aZN0qfMKmgWp/nFkVpzRVBcIYKUOzD6UOTmxWS5sImjd2ICOHUVZ5m9Q1uz/qTsMTB1uipaR905eWoeSwIMQCeWKkCeCNvXQuCbI94z4gDw0K6KtHGY43Tv68udHwdvqpTaph6QOudbF8ZilWM+XeqGGk6OI/8MxHJJffls7B18kYlQAaSv18Z1pRibLaFcTwS1aSWyzoL3juutecGLkxqWTliLt0Jt3fnyfbNBGXaMQ9rH+iXWm4VkGBnGjlF2yu54GNvfdftTfwST1jPjrqlSMgErjAF0Gg=
  app:
    develop: auto-mart-ng
